[package]
name = "mozim"
version = "0.1.0"
edition = "2021"

[lib]
name = "mozim"
path = "src/lib.rs"

[[bin]]
name = "mzc"
path = "src/mzc.rs"

[dependencies]
rand = "0.8.5"
libc = "0.2.119"
nispor = { git = "https://github.com/nispor/nispor" }
byteorder = "1.4.3"
#dhcproto = "0.6.0"
dhcproto = {git = "https://github.com/cathay4t/dhcproto", branch="fix_chaddr"}
log = "0.4.14"
etherparse = "0.10.1"
nix = "0.23.1"
env_logger = "0.9.0"
clap = { version = "3.1.2", features = ["derive"] }
